version: '3.8'

services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: urfmp-postgres
    environment:
      POSTGRES_DB: urfmp
      POSTGRES_USER: urfmp
      POSTGRES_PASSWORD: urfmp-dev-2024
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./infrastructure/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urfmp"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: urfmp-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: urfmp-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: urfmp
      RABBITMQ_DEFAULT_PASS: urfmp-dev-2024
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: urfmp-clickhouse
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native protocol
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./infrastructure/clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      CLICKHOUSE_DB: urfmp
      CLICKHOUSE_USER: urfmp
      CLICKHOUSE_PASSWORD: urfmp-dev-2024
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: urfmp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: urfmp-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log

  # API Service
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    container_name: urfmp-api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://urfmp:urfmp-dev-2024@postgres:5432/urfmp
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://urfmp:urfmp-dev-2024@rabbitmq:5672
    depends_on:
      - postgres
      - redis
      - rabbitmq
    volumes:
      - ./services/api:/app/services/api
      - ./packages:/app/packages
      - /app/node_modules
      - /app/services/api/node_modules
    command: npx tsx watch services/api/src/index.ts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Web Frontend
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    container_name: urfmp-web
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:3000
      VITE_COMPANY_NAME: ${VITE_COMPANY_NAME:-URFMP}
      VITE_PRODUCT_NAME: ${VITE_PRODUCT_NAME:-URFMP}
      VITE_COMPANY_NAME_SHORT: ${VITE_COMPANY_NAME_SHORT:-URFMP}
      VITE_PRODUCT_FULL_NAME: ${VITE_PRODUCT_FULL_NAME:-Universal Robot Fleet Management Platform}
      VITE_TAGLINE: ${VITE_TAGLINE:-The Stripe of Robotics}
      VITE_DESCRIPTION: ${VITE_DESCRIPTION:-Monitor any robot in 7 lines of code}
    depends_on:
      - api
    volumes:
      - ./web:/app/web
      - ./packages:/app/packages
      - /app/node_modules
      - /app/web/node_modules
    command: sh -c "cd /app/web && npx vite --host 0.0.0.0 --port 3001"

  # Development tools
  adminer:
    image: adminer:latest
    container_name: urfmp-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres

volumes:
  postgres-data:
  redis-data:
  rabbitmq-data:
  clickhouse-data:
  kafka-data:
  zookeeper-data:
  zookeeper-logs:

networks:
  default:
    name: urfmp-network
    driver: bridge
