#!/bin/bash

TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiYmJiYmJiYi1iYmJiLWJiYmItYmJiYi1iYmJiYmJiYmJiYmIiLCJvcmciOiJhYWFhYWFhYS1hYWFhLWFhYWEtYWFhYS1hYWFhYWFhYWFhYWEiLCJlbWFpbCI6ImFkbWluQHVyZm1wLmNvbSIsInJvbGUiOiJhZG1pbiIsInBlcm1pc3Npb25zIjpbInJvYm90LnZpZXciLCJyb2JvdC5jcmVhdGUiLCJyb2JvdC51cGRhdGUiLCJyb2JvdC5kZWxldGUiLCJ0ZWxlbWV0cnkudmlldyIsInRlbGVtZXRyeS53cml0ZSIsIm1haW50ZW5hbmNlLnZpZXciLCJtYWludGVuYW5jZS5jcmVhdGUiLCJtYWludGVuYW5jZS51cGRhdGUiLCJtYWludGVuYW5jZS5kZWxldGUiLCJ1c2VyLnZpZXciLCJ1c2VyLmNyZWF0ZSIsInVzZXIudXBkYXRlIiwidXNlci5kZWxldGUiLCJvcmdhbml6YXRpb24udmlldyIsIm9yZ2FuaXphdGlvbi51cGRhdGUiLCJhbGVydC52aWV3IiwiYWxlcnQuY3JlYXRlIiwiYWxlcnQudXBkYXRlIiwiYXBpX2tleS52aWV3IiwiYXBpX2tleS5jcmVhdGUiLCJhcGlfa2V5LmRlbGV0ZSJdLCJzY29wZSI6WyJyb2JvdC52aWV3Iiwicm9ib3QuY3JlYXRlIiwicm9ib3QudXBkYXRlIiwicm9ib3QuZGVsZXRlIiwidGVsZW1ldHJ5LnZpZXciLCJ0ZWxlbWV0cnkud3JpdGUiLCJtYWludGVuYW5jZS52aWV3IiwibWFpbnRlbmFuY2UuY3JlYXRlIiwibWFpbnRlbmFuY2UudXBkYXRlIiwibWFpbnRlbmFuY2UuZGVsZXRlIiwidXNlci52aWV3IiwidXNlci5jcmVhdGUiLCJ1c2VyLnVwZGF0ZSIsInVzZXIuZGVsZXRlIiwib3JnYW5pemF0aW9uLnZpZXciLCJvcmdhbml6YXRpb24udXBkYXRlIiwiYWxlcnQudmlldyIsImFsZXJ0LmNyZWF0ZSIsImFsZXJ0LnVwZGF0ZSIsImFwaV9rZXkudmlldyIsImFwaV9rZXkuY3JlYXRlIiwiYXBpX2tleS5kZWxldGUiXSwiYXVkIjoidXJmbXAtYXBpIiwiaXNzIjoidXJmbXAiLCJpYXQiOjE3NTk0MjIxMjAsImV4cCI6MTc1OTQyNTcyMH0.HWI_4sCMnK7nBmDww4S9bEh-RvLEG_FmcqQFgnv9otE"

echo "Fetching robots with JWT Bearer token..."
curl -s https://urfmpapi-production.up.railway.app/api/v1/robots \
  -H "Authorization: Bearer $TOKEN" | jq

echo ""
echo "Fetching robots with API Key..."
curl -s https://urfmpapi-production.up.railway.app/api/v1/robots \
  -H "X-API-Key: urfmp_dev_9f8e7d6c5b4a3910efabcdef12345678" | jq
